/* data.js — constantes do curso */

const PROF_LOGIN    = 'Prof';
const PROF_PASSWORD = 'Edu321';
const PROF_NAME     = 'Eduardo';

const MONTHS_DATA = [
 {
    num: 1, name: 'Janeiro',
    emoji: '🎵', tag: 'Fundamentos',
    desc: 'Embocadura 1ª e 2ª, posicionamento correto e Notas da 1ª, 2ª e 3ª Oitava.',
    fullDesc: 'O ponto de partida. Você vai construir a base de tudo: a relação correta com a embocadura, a postura com o instrumento e as primeiras notas da flauta — o alicerce de toda a técnica futura.',
    pillar: 'Teoria',
    objectives: [
  'Estudar a sonoridade: produzir timbre centrado, cheio e sem ruído de ar',
  'Controlar a embocadura com precisão: ajustar abertura e direção do ar para estabilidade em diferentes dinâmicas (piano a forte)',
  'Sustentar notas longas por 5–10 segundos com afinação estável e sem oscilações',
  'Manter postura corporal consistente durante toda a prática (sem colapsos ao longo do tempo)',
  'Executar transições suaves entre notas (Si–Lá–Sol–Fá–Mi) sem “quebras” no som',
  'Iniciar controle básico de afinação — ajustar micro variações com embocadura e ar',
  'Explorar 1ª, 2ª e início da 3ª oitava com consciência de apoio de ar (sem tensão)',
  'Desenvolver controle de ataque (início da nota) sem golpes de ar excessivos',
  'Manter relaxamento total das mãos mesmo em mudanças de posição',
  'Gravar e analisar o próprio som identificando: ruído de ar e instabilidade ',
  'Utilizar o app Jogo das Escalas com foco em precisão e tempo de resposta',
],
    tip: 'Não se apresse — um som belo e limpo vale mais do que muitas notas feias. Use o gravador de voz para ouvir seu próprio som e se corrigir.',
    pdfRef: 'Conteúdo do Módulo 1 • Pilares do Aprendizado (p.4) • Posições (p.6–7) • Notas (p.8)',
  },
  { num:2,  name:'Fevereiro', emoji:'🎶', tag:'1ª, 2ª e 3ª Oitava', desc:'Expansão do registro — domínio das três oitavas.',           pillar:'Prática',
    fullDesc:'Com a base de janeiro, você expande o alcance passando pelas oitavas. A passagem exige controle de ar e lábio.',
    objectives:['Dominar completamente a 1ª oitava','Notas longas de Moyse — controle de sonoridade','Passagem para a 2ª oitava com controle de ar','Início das notas da 3ª oitava','Ligaduras entre oitavas','Escalas de Dó e Sol Maior nas 3 oitavas','Prática diária com metrônomo e gravação'],
    tip:'A passagem de oitava se vence com paciência. Aumente a velocidade do ar, não a pressão dos lábios.' },
  { num:3,  name:'Março',     emoji:'🎤', tag:'Prova 1º Semestre',  desc:'Louvores aplicados + avaliação do 1º semestre.',            pillar:'Constância',
    fullDesc:'Integre o aprendizado no contexto do louvor. O mês fecha com a prova do primeiro semestre.',
    objectives:['Tocar ao menos 3 louvores com boa fluidez','Demonstrar controle das 3 oitavas','Prova: embocadura, postura e sonoridade','Prova: mínimo 2 louvores completos','Gravar as sessões para autocrítica'],
    tip:'Escolha louvores que você já conhece — isso libera o foco para a técnica.' },
  { num:4,  name:'Maio',      emoji:'🔊', tag:'Qualidade Sonora',   desc:'Afinação, projeção, mecânica e repertório clássico.',       pillar:'Prática',
    fullDesc:'Salto de qualidade: afinação com afinador, projeção sonora, mecânica avançada e grandes compositores.',
    objectives:['Treinos de afinação com SoundCorset','Projeção sonora em ambientes maiores','Mecânica: arpejos com variações de BPM','Notas longas de Moyse — timbre e projeção','Introdução a Bach, Mozart e Patápio Silva','Escutar Altamiro Carrilho como referência','Rotina: 30min escalas + 30min notas longas + 30min mecânica + 30min peça'],
    tip:'Estudar com concentração e atenção aos detalhes, com constância, vale mais que 10h massivas.' },
  { num:5,  name:'Junho',     emoji:'📜', tag:'Partitura I',        desc:'Introdução à leitura de partitura.',                        pillar:'Teoria',
    fullDesc:'Você começa a ler música escrita. A partitura é a linguagem universal da música.',
    objectives:['Notas reais (Dó–Si) e cifradas (C–B) na pauta','Figuras de duração: semibreve, mínima, semínima, colcheia','Pausas e compasso 4/4 com metrônomo','Leitura de melodias simples na 1ª oitava','Praticar "Clamo a Ti" — compasso 4/4','Cantarolar a nota antes de tocar','Usar app de escalas para memorizar notas'],
    tip:'Solfeje antes de tocar: cante a nota primeiro. Isso acelera o aprendizado.' },
  { num:6,  name:'Julho',     emoji:'📖', tag:'Partitura II',       desc:'Leitura fluida e introdução à primeira vista.',              pillar:'Teoria',
    fullDesc:'Leitura fluida em 2 oitavas, acidentes, dinâmica e leitura à primeira vista.',
    objectives:['Notas com acidentes na partitura (# e ♭)','Leitura em 2 oitavas com partitura','Dinâmica: forte, piano, crescendo, decrescendo','Compasso 6/8: contagem 1,2,3–4,5,6','Exercícios de primeira vista — isolar frases','Louvores completos com partitura'],
    tip:'Primeira vista: olhe 1 compasso à frente enquanto toca o atual.' },
  { num:7,  name:'Agosto',    emoji:'🏆', tag:'Prova 2º Semestre',  desc:'Prova tripla: partitura, primeira vista e peça erudita.',   pillar:'Constância',
    fullDesc:'A maior avaliação do ano. Três provas que mostram a evolução completa.',
    objectives:['Prova 1: Louvores com partitura (fluência e expressão)','Prova 2: Leitura à primeira vista','Prova 3: Peça erudita — Bach, Mozart ou Patápio Silva','Afinação, projeção e qualidade sonora','Apresentação com postura e confiança','Gravar a prova para análise'],
    tip:'Grave-se nas 3 semanas anteriores. Compare com o início do curso — a evolução vai te surpreender.' },
  { num:8,  name:'Setembro',  emoji:'🎼', tag:'Harmonia em Trio',   desc:'Projeto de harmonia com 3 alunos.',                         pillar:'Prática',
    fullDesc:'Música é coletiva. Você toca em conjunto, desenvolvendo escuta harmônica e sincronia.',
    objectives:['Introdução à harmonia a 3 vozes','Leitura de arranjo a 3 flautas','Afinação coletiva e sincronia de tempo','Escuta ativa dos colegas','Ensaios semanais','Gravar ensaios para análise coletiva'],
    tip:'No ensemble, ouvir é tão importante quanto tocar.' },
  { num:9,  name:'Outubro',   emoji:'🎵', tag:'Projeto de Harmonia', desc:'Polimento e conclusão do projeto em trio.',                 pillar:'Prática',
    fullDesc:'Aprofundamento do trio: polimento, dinâmica coletiva e preparação para apresentação.',
    objectives:['Polimento do repertório do trio','Dinâmica coletiva: crescendos em conjunto','Afinação refinada entre as 3 vozes','Ensaio geral para apresentação','Gravação de ensaio para autocrítica'],
    tip:'Grave os ensaios — seja honesto com os colegas sobre o que pode melhorar.' },
  { num:10, name:'Nov/Dez',   emoji:'🎬', tag:'Projeto Final',      desc:'Gravação profissional em dupla com o professor.',           pillar:'Constância',
    fullDesc:'O encerramento do ano. Gravação de um louvor integrando TODOS os conteúdos aprendidos.',
    objectives:['Escolha colaborativa do louvor (aluno + professor)','Preparação técnica e expressiva da peça final','Gravação profissional','Integração: teoria, prática e constância','Entrega do produto final — sua música'],
    tip:'Toque com emoção — é sua história musical. Compare com a gravação do primeiro mês.' },
];

const SCALES_DATA = [
  // Quintas
  { key:'C',  name:'Dó',   circuit:'fifths', info:'C Maior (0#)', notes:'Dó · Ré · Mi · Fá · Sol · Lá · Si · Dó',          cipher:'C · D · E · F · G · A · B · C',             acids:'—',                              louvor:'Base do estudo', detail:'Sem acidentes. Ponto de partida absoluto. A 5ª nota (Sol) é a raiz da próxima escala.' },
  { key:'G',  name:'Sol',  circuit:'fifths', info:'G Maior (1#)', notes:'Sol · Lá · Si · Dó · Ré · Mi · Fá# · Sol',         cipher:'G · A · B · C · D · E · F# · G',            acids:'Fá#',                            louvor:'⭐ Muito usada',  detail:'Nova nota: Fá#. A 5ª nota (Ré) é a raiz da próxima. Domine o Fá# isoladamente.' },
  { key:'D',  name:'Ré',   circuit:'fifths', info:'D Maior (2#)', notes:'Ré · Mi · Fá# · Sol · Lá · Si · Dó# · Ré',         cipher:'D · E · F# · G · A · B · C# · D',           acids:'Fá# · Dó#',                      louvor:'⭐ Usada',        detail:'Nova nota: Dó#. A 5ª nota (Lá) é a raiz da próxima. O Dó# aparece na 3ª oitava.' },
  { key:'A',  name:'Lá',   circuit:'fifths', info:'A Maior (3#)', notes:'Lá · Si · Dó# · Ré · Mi · Fá# · Sol# · Lá',        cipher:'A · B · C# · D · E · F# · G# · A',          acids:'Fá# · Dó# · Sol#',               louvor:'Moderada',       detail:'Nova nota: Sol#. A 5ª nota (Mi) é a raiz da próxima. Use afinador nos agudos.' },
  { key:'E',  name:'Mi',   circuit:'fifths', info:'E Maior (4#)', notes:'Mi · Fá# · Sol# · Lá · Si · Dó# · Ré# · Mi',       cipher:'E · F# · G# · A · B · C# · D# · E',         acids:'Fá# · Dó# · Sol# · Ré#',         louvor:'Pouco usada',    detail:'Nova nota: Ré#. A 5ª nota (Si) é a raiz da próxima. Memória muscular sólida.' },
  { key:'B',  name:'Si',   circuit:'fifths', info:'B Maior (5#)', notes:'Si · Dó# · Ré# · Mi · Fá# · Sol# · Lá# · Si',      cipher:'B · C# · D# · E · F# · G# · A# · B',        acids:'Fá# · Dó# · Sol# · Ré# · Lá#',  louvor:'Avançada',       detail:'Nova nota: Lá#. A 5ª nota (Fá#) é a raiz da próxima. Enarmônica de Dó♭.' },
  { key:'Fs', name:'Fá#',  circuit:'fifths', info:'F# Maior (6#)',notes:'Fá# · Sol# · Lá# · Si · Dó# · Ré# · Mi# · Fá#',   cipher:'F# · G# · A# · B · C# · D# · E# · F#',     acids:'Fá# · Dó# · Sol# · Ré# · Lá# · Mi#', louvor:'Avançada', detail:'Nova nota: Mi# (=Fá). Seis sustenidos — enarmônica de Sol♭.' },
  // Quartas
  { key:'F',  name:'Fá',   circuit:'fourths',info:'F Maior (1♭)', notes:'Fá · Sol · Lá · Si♭ · Dó · Ré · Mi · Fá',          cipher:'F · G · A · B♭ · C · D · E · F',           acids:'Si♭',                            louvor:'⭐ Hinos',        detail:'Nova nota: Si♭. A 4ª nota é sempre bemolizada. A 4ª nota (Si♭) é raiz da próxima.' },
  { key:'Bb', name:'Si♭',  circuit:'fourths',info:'B♭ Maior (2♭)',notes:'Si♭ · Dó · Ré · Mi♭ · Fá · Sol · Lá · Si♭',        cipher:'B♭ · C · D · E♭ · F · G · A · B♭',         acids:'Si♭ · Mi♭',                      louvor:'🎯 A MAIS USADA!',detail:'🎯 TONALIDADE MAIS COMUM NO LOUVOR! Memorize prioritariamente. A 4ª nota (Mi♭) é raiz da próxima.' },
  { key:'Eb', name:'Mi♭',  circuit:'fourths',info:'E♭ Maior (3♭)',notes:'Mi♭ · Fá · Sol · Lá♭ · Si♭ · Dó · Ré · Mi♭',       cipher:'E♭ · F · G · A♭ · B♭ · C · D · E♭',        acids:'Si♭ · Mi♭ · Lá♭',                louvor:'⭐⭐ 2ª mais usada',detail:'Nova nota: Lá♭. Segunda tonalidade mais usada no louvor. Controle os bemóis agudos.' },
  { key:'Ab', name:'Lá♭',  circuit:'fourths',info:'A♭ Maior (4♭)',notes:'Lá♭ · Si♭ · Dó · Ré♭ · Mi♭ · Fá · Sol · Lá♭',     cipher:'A♭ · B♭ · C · D♭ · E♭ · F · G · A♭',      acids:'Si♭ · Mi♭ · Lá♭ · Ré♭',          louvor:'Arranjos elaborados',detail:'Nova nota: Ré♭. Com 4 bemóis, exige memória muscular — pratique devagar.' },
  { key:'Db', name:'Ré♭',  circuit:'fourths',info:'D♭ Maior (5♭)',notes:'Ré♭ · Mi♭ · Fá · Sol♭ · Lá♭ · Si♭ · Dó · Ré♭',    cipher:'D♭ · E♭ · F · G♭ · A♭ · B♭ · C · D♭',     acids:'Si♭ · Mi♭ · Lá♭ · Ré♭ · Sol♭',  louvor:'Avançada',       detail:'Nova nota: Sol♭. Enarmônica de Dó# (7#). Grave-se para verificar cada nota.' },
  { key:'Gb', name:'Sol♭', circuit:'fourths',info:'G♭ Maior (6♭)',notes:'Sol♭ · Lá♭ · Si♭ · Dó♭ · Ré♭ · Mi♭ · Fá · Sol♭',  cipher:'G♭ · A♭ · B♭ · C♭ · D♭ · E♭ · F · G♭',   acids:'Si♭ · Mi♭ · Lá♭ · Ré♭ · Sol♭ · Dó♭', louvor:'Avançada', detail:'Nova nota: Dó♭ (=Si). Seis bemóis — enarmônica de Fá#.' },
  { key:'Cb', name:'Dó♭',  circuit:'fourths',info:'C♭ Maior (7♭)',notes:'Dó♭ · Ré♭ · Mi♭ · Fá♭ · Sol♭ · Lá♭ · Si♭♭ · Dó♭', cipher:'C♭ · D♭ · E♭ · F♭ · G♭ · A♭ · B♭♭ · C♭', acids:'Si♭ · Mi♭ · Lá♭ · Ré♭ · Sol♭ · Dó♭ · Fá♭', louvor:'Raramente usada', detail:'Sete bemóis — enarmônica de Si Maior. Estudo avançado.' },
];
